# Generated by Django 2.1.5 on 2021-05-27 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product')),
                ('unit_price', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(10000000.0)], verbose_name='Unit Price (R$)')),
                ('multiple', models.IntegerField(default='', null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
