# Generated by Django 2.1.5 on 2021-06-02 17:31

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_price', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(10000000.0)], verbose_name='Suggested Price (R$)')),
                ('amount', models.IntegerField(blank=True, default=1, null=True, verbose_name='Amount')),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product')),
                ('unit_price', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(10000000.0)], verbose_name='Unit Price (R$)')),
                ('multiple', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Multiple')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
#try again