# Generated by Django 2.1.5 on 2021-05-31 14:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_price', models.FloatField(validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(10000000.0)], verbose_name='Suggested Price (R$)')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Amount')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
