# Generated by Django 2.1.5 on 2021-05-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20210527_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='multiple',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
