# Generated by Django 2.1.5 on 2021-06-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20210601_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiple',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Multiple'),
        ),
    ]
