# Generated by Django 2.1.5 on 2021-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_auto_20210527_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='multiple',
            field=models.IntegerField(blank=True, null=True, verbose_name='Multiple'),
        ),
    ]
